name: MacOS-VNC

on: [push, workflow_dispatch]

jobs:
  enable-vnc:
    runs-on: macos-latest

    steps:
    - name: Enable Screen Sharing (VNC)
      run: |
        echo "Activating Screen Sharing..."
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes \
          -clientopts -setvncpw -vncpw your_password -restart -agent -privs -all
        echo "Screen Sharing activated."

    - name: Display Connection Info
      run: |
        IP=$(ipconfig getifaddr en0)
        echo "Connect to this macOS runner using VNC at ${IP}:5900"
        echo "Password: your_password"

    - name: Keep Session Active for 6 Hours
      run: |
        echo "Keeping session active for 6 hours..."
        sleep 21600  # 6 hours in seconds
