name: MacOS-ChromeRemoteDesktop

on: [push, workflow_dispatch]

jobs:
  setup-crd:
    runs-on: macos-latest

    steps:
    - name: Install Chrome Browser
      run: |
        brew install --cask google-chrome
        echo "Google Chrome installed successfully."

    - name: Install Chrome Remote Desktop
      run: |
        brew install --cask chrome-remote-desktop-host
        echo "Chrome Remote Desktop installed successfully."

    - name: Start Chrome Remote Desktop Service
      run: |
        /Applications/Google\ Chrome\ Remote\ Desktop\ Host.app/Contents/MacOS/chrome-remote-desktop-host --start-host \
          --code="4/0AanRRrsI9aJ8n5_q2sjRMgBzIlPDdqswSgcHJ1bZ0OmE8wz2SSizJDqugJdKdh-XexSF3g" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name="GitHubRunner" \
          --pin=123456
        echo "Chrome Remote Desktop configured."

    - name: Keep Session Active for 6 Hours
      run: |
        echo "Keeping session active for 6 hours..."
        sleep 21600  # 6 hours
