name: MacOS-AnyDesk

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "Homebrew installed successfully."

    - name: Install AnyDesk
      run: |
        brew install --cask anydesk
        if [ ! -d "/Applications/AnyDesk.app" ]; then
          echo "AnyDesk was not installed. Exiting."
          exit 1
        fi
        echo "AnyDesk installed successfully."

    - name: Launch AnyDesk
      run: |
        if [ -d "/Applications/AnyDesk.app" ]; then
          open -a /Applications/AnyDesk.app
          echo "AnyDesk launched successfully."
        else
          echo "AnyDesk application not found. Exiting."
          exit 1
        fi
        sleep 10

    - name: Keep the Session Active
      run: |
        echo "Keeping session active for 6 hours..."
        sleep 21600
