name: MacOS-AnyDesk

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "Homebrew installed successfully."

    - name: Install AnyDesk
      run: |
        brew install --cask anydesk || echo "AnyDesk installation failed."
        brew list --cask | grep -q anydesk && echo "AnyDesk is installed." || echo "AnyDesk is not installed."

    - name: Launch AnyDesk
      run: |
        if open -a AnyDesk; then
          echo "AnyDesk launched successfully."
        else
          echo "Unable to find AnyDesk. Installation may have failed."
          exit 1
        fi
        sleep 10

    - name: Keep the Session Active
      run: |
        echo "Keeping session active for 6 hours..."
        sleep 21600
