name: MacOS-AnyDesk

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install AnyDesk
      run: |
        brew install --cask anydesk

    - name: Start AnyDesk Daemon
      run: |
        open -a AnyDesk
        sleep 10

    - name: Get AnyDesk Address
      run: |
        echo "Fetching AnyDesk ID..."
        cat ~/Library/Application\ Support/AnyDesk/service.conf | grep 'ad_id'

    - name: Keep the Session Active
      run: |
        echo "Keeping session active for 6 hours..."
        sleep 21600
