name: MacOS-RDP

on: [push, workflow_dispatch]

jobs:
  enable-rdp:
    runs-on: macos-latest

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "Homebrew installed successfully."

    - name: Install xrdp and XQuartz
      run: |
        brew install --cask xquartz
        brew install xrdp
        sudo launchctl load -w /Library/LaunchAgents/xrdp.plist
        echo "xrdp and XQuartz installed successfully."

    - name: Start xrdp Service
      run: |
        sudo /opt/homebrew/bin/xrdp --nodaemon &
        echo "xrdp service started."

    - name: Display Connection Info
      run: |
        IP=$(ipconfig getifaddr en0)
        echo "Connect to this macOS runner using RDP at ${IP}:3389"
